"""Add user and task models

Revision ID: 8db8b9b6f13c
Revises: 
Create Date: 2026-08-04 16:05:47.079642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db8b9b6f13c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', name='taskstatus'), nullable=True))
    op.add_column('tasks', sa.Column('type', sa.Enum('FEATURE', 'BUG', 'TASK', name='tasktype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'type')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
